package es.alesqui.intelligence.dto.dashboard;

import es.alesqui.intelligence.dto.conversation.LastConversationInfo;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Aggregated activity metrics for the authenticated user, used by the Dashboard activity widget.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ActivityInfo {

    /** Total number of conversations the user has started across all time. */
    private long totalConversations;

    /** Number of conversations started within the last 7 calendar days. */
    private long conversationsLast7Days;

    /** Total number of individual messages sent across all conversations. */
    private long totalMessages;

    /** Total number of charts generated by the user. */
    private long chartsGenerated;

    /** Key details of the most recently active conversation, or null if none exists. */
    private LastConversationInfo lastConversation;
}
