package es.alesqui.intelligence.model.audit;

import java.time.Instant;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an audit log entry in the MongoDB audit_logs collection.
 * 
 * This entity captures comprehensive information about administrative actions
 * performed in the system, including user operations, group management,
 * and API access changes. Each log entry provides a complete audit trail
 * for compliance, security monitoring, and troubleshooting purposes.
 * 
 * Automatic Retention Policy (TTL):
 * Audit logs are automatically deleted after the configured retention period.
 * The retention period is configurable via {@code audit.retention.days} property
 * in application.properties (default: 730 days / 2 years).
 * MongoDB's TTL background task runs every 60 seconds to remove expired documents.
 * 
 * To change retention period:
 * Set {@code audit.retention.days=365} in application.properties for 1 year retention.
 * Note: Changes require application restart and index recreation.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document("audit_logs")
@CompoundIndexes({
    @CompoundIndex(name = "timestamp_idx", def = "{ 'timestamp': -1 }"),
    @CompoundIndex(name = "actor_action_idx", def = "{ 'actorUsername': 1, 'action': 1 }"),
    @CompoundIndex(name = "entity_idx", def = "{ 'entityType': 1, 'entityId': 1 }")
})
public class AuditLog {
    
    /**
     * Unique identifier for this audit log entry.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;
    
    /**
     * Timestamp when the audited action occurred.
     * Stored in UTC format for consistency across time zones.
     * 
     * This field has a TTL (Time To Live) index configured to automatically
     * delete audit logs after the retention period specified in configuration.
     * The index is created programmatically at application startup.
     */
    private Instant timestamp;
    
    /**
     * Username of the user who performed the action.
     * This corresponds to the authenticated user's username from the JWT token.
     */
    private String actorUsername;
    
    /**
     * User ID of the user who performed the action.
     * Stored separately to maintain referential integrity even if username changes.
     */
    private String actorUserId;
    
    /**
     * Type of action performed (e.g., USER_CREATED, GROUP_DELETED).
     * See {@link AuditAction} enum for all possible values.
     */
    private AuditAction action;
    
    /**
     * Type of entity affected by this action (e.g., USER, GROUP, API).
     * See {@link EntityType} enum for all possible values.
     */
    private EntityType entityType;
    
    /**
     * Unique identifier of the entity affected by this action.
     * This is the database ID of the user, group, API, etc.
     */
    private String entityId;
    
    /**
     * Human-readable name or identifier of the affected entity.
     * Examples: username for users, group name for groups, API name for APIs.
     * This provides quick identification without requiring additional queries.
     */
    private String entityName;
    
    /**
     * Additional details about the action in JSON or plain text format.
     * This field is optional and can contain contextual information
     * that doesn't fit in the structured fields.
     */
    private String details;
    
    /**
     * IP address of the client that initiated the action.
     * Extracted from the HTTP request headers (X-Forwarded-For, X-Real-IP, or remote address).
     * Useful for security analysis and geographic tracking.
     */
    private String ipAddress;
    
    /**
     * User-Agent string from the HTTP request headers.
     * Identifies the browser/client application used to perform the action.
     * Helps in identifying suspicious activity patterns.
     */
    private String userAgent;
    
    /**
     * Result of the operation (SUCCESS or FAILURE).
     * See {@link AuditResult} enum for possible values.
     */
    private AuditResult result;
    
    /**
     * Error message if the operation failed (result = FAILURE).
     * Null or empty for successful operations.
     * Contains the exception message or error description for failed operations.
     */
    private String errorMessage;
    
    /**
     * JSON representation of the entity's state before the operation.
     * Populated for UPDATE and DELETE operations to track what was changed or removed.
     * Stored as a JSON string to maintain flexibility across different entity types.
     */
    private String previousData;
    
    /**
     * JSON representation of the entity's state after the operation.
     * Populated for CREATE and UPDATE operations to track what was added or changed.
     * Stored as a JSON string to maintain flexibility across different entity types.
     */
    private String newData;
}
