package es.alesqui.intelligence.model.access;

import java.time.Instant;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

/**
 * Represents a logical collection of users and APIs in MongoDB.
 * Groups determine which APIs are visible to a user.
 * An API that is not linked to any group is considered public by default.
 */
@Data
@Document("groups")
public class Group {

    /**
     * The unique identifier for the group document, generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Stable unique code used as an internal identifier (slug-like).
     */
    @Indexed(unique = true)
    private String code;

    /**
     * Human readable name of the group.
     */
    private String name;

    /**
     * Optional description of the group's purpose.
     */
    private String description;

    /**
     * Creation timestamp for auditing. Set by application code as needed.
     */
    private Instant createdAt;

}
