package es.alesqui.intelligence.dto.conversation;

import es.alesqui.intelligence.dto.chat.response.ChartData;
import lombok.Builder;
import lombok.Data;
import java.time.Instant;
import java.util.List;

/**
 * A Data Transfer Object (DTO) that represents a single, complete "turn" or
 * exchange within a conversation.
 *
 * This includes the user's prompt and the full response from the assistant,
 * which may consist of text, a chart, and the technical reasoning. A list of
 * these objects is used to reconstruct the entire view of a past conversation.
 */
@Data
@Builder
public class ConversationDetailDTO {
	
	/**
     * The unique ID of this specific ConversationRecord.
     */
    private String id;

    /**
     * The original, unmodified prompt or question submitted by the user for this turn.
     */
    private String userPrompt;

    /**
     * The final textual response generated by the assistant. This content is
     * displayed to the user, often alongside other elements like charts.
     */
    private String responseText;

    /**
     * The data configuration for a chart, if one was generated in the response.
     * This field will be null if no chart was part of the assistant's answer.
     */
    private ChartData responseChart;

    /**
     * The formatted step-by-step reasoning narrative produced by the AI agent.
     * This is intended for the IT role to debug and understand the agent's
     * decision-making process.
     */
    private String stepByStepReasoning;

    /**
     * The exact timestamp when this interaction occurred.
     */
    private Instant timestamp;

    /**
     * A boolean flag indicating whether this specific turn resulted in a
     * processing error. Useful for highlighting problematic interactions in the UI.
     */
    private boolean isError;
    
    /**
     * The user's feedback, if any.
     */
    private String userFeedbackComment;
    
    /**
     * Internal notes, if any (only for IT).
     */
    private List<String> internalNotes;
}
