package es.alesqui.intelligence.model.conversation;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import es.alesqui.intelligence.dto.chat.response.ChartData;

import java.time.Instant;

/**
 * Represents a single interaction record within a user conversation in the Alesqui Intelligence application.
 *
 * This document captures the complete lifecycle of a query:
 * 1. The user's input (prompt).
 * 2. The final answer generated by the AI agent.
 * 3. The internal step-by-step reasoning process followed by the agent.
 * 4. The status of the interaction, for auditing and support purposes.
 *
 * It is stored in the "conversations" collection in MongoDB.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document("conversations")
public class ConversationRecord {

    /**
     * The unique identifier for the conversation record, automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * An identifier used to group multiple interactions (turns) belonging to the same conversation.
     * This field is indexed for efficient retrieval of an entire chat history.
     */
    @Indexed
    private String conversationId;

    /**
     * The username of the user who initiated the interaction.
     * This field is indexed to allow quick lookups of all conversations for a specific user.
     */
    @Indexed
    private String username;

    /**
     * The exact date and time when the interaction was recorded, stored in UTC.
     * This field is indexed to enable filtering and sorting by date.
     */
    @Indexed
    private Instant timestamp;

    /**
     * The original, unmodified question or prompt submitted by the user.
     */
    private String userPrompt;

    /**
     * The textual part of the final answer provided to the user.
     * This is the content that appears alongside any data visualizations.
     */
    private String responseText;

    /**
     * The chart data structure provided to the user for visualization.
     * It will be null if no chart was generated for this interaction.
     */
    private ChartData responseChart;

    /**
     * The detailed reasoning process the AI agent followed to arrive at the final answer.
     * This is crucial for debugging by the IT team. It is stored as a flexible Object
     * to accommodate various structures (e.g., a JSON string or a nested Map).
     */
    private Object stepByStepReasoning;

    /**
     * The current status of this interaction record.
     * Used for tracking and filtering, especially for the IT support panel
     * (e.g., finding all REPORTED_BY_USER interactions).
     */
    private ConversationStatus status;
}
