package es.alesqui.intelligence.model.core;

import java.time.Instant;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import es.alesqui.intelligence.model.core.enums.Role;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a user account in the Alesqui Intelligence application.
 *
 * This class serves a dual purpose:
 * 1. It is a MongoDB document that stores user information in the "users" collection.
 * 2. It implements the Spring Security `UserDetails` interface, allowing the framework
 * to handle authentication and authorization based on this model.
 */
@Data 
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document("users")
public class User implements UserDetails {

    /**
     * The unique identifier for the user document, automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The user's unique username, used for logging in.
     * This field is indexed to ensure fast lookups and enforce uniqueness.
     */
    @Indexed(unique = true)
    private String username;

    /**
     * The user's password. It must be stored in a securely hashed format,
     * such as BCrypt.
     */
    private String password;

    /**
     * A set of roles assigned to the user. Roles determine the user's
     * permissions and access level within the application.
     */
    @Builder.Default // Ensures the field is initialized even when using the builder
    private Set<Role> roles = new HashSet<>();

    /**
     * Creation timestamp for auditing. Records when the user account was created.
     */
    private Instant createdAt;


    // --- UserDetails interface implementation ---

    /**
     * Returns the authorities granted to the user.
     * Spring Security uses this information for role-based authorization.
     *
     * @return A collection of GrantedAuthority objects, derived from the user's roles.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // Ensure roles is not null before streaming
        if (roles == null) {
            return Set.of();
        }
    return roles.stream()
        .map(role -> new SimpleGrantedAuthority(role.name()))
        .collect(Collectors.toList());
    }

    /**
     * Indicates whether the user's account has expired.
     * For this implementation, accounts never expire.
     *
     * @return always true.
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is locked or unlocked.
     * For this implementation, accounts are never locked.
     *
     * @return always true.
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether the user's credentials (password) has expired.
     * For this implementation, credentials never expire.
     *
     * @return always true.
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is enabled or disabled.
     * For this implementation, users are always enabled.
     *
     * @return always true.
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}