package es.alesqui.intelligence.model.api_spec.postman;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;
import java.util.List;

import es.alesqui.intelligence.model.api_spec.ApiSpecDocument;

/**
 * Wrapper entity for Postman Collections stored in MongoDB.
 * 
 * This class serves as a document wrapper around the Postman Collection model,
 * providing additional metadata, lifecycle management, and utility methods
 * for better organization and tracking of Postman collections in the database.
 * 
 * The wrapper separates concerns by maintaining collection metadata (name, version, dates)
 * independently from the actual Postman collection structure, enabling better
 * search capabilities, audit trails, and collection management.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "postman_collection_documents")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PostmanDocument implements ApiSpecDocument {
  
  /**
   * Unique identifier of the document in MongoDB.
   * Automatically generated by MongoDB when the document is persisted.
   */
  @Id
  private String id;
  
  /**
   * Human-readable name for the collection document.
   * This can be different from the collection's internal name and is used
   * for display and search purposes in the application.
   */
  @Field("name")
  @JsonProperty("name")
  @Indexed(unique = true)
  private String name;
  
  /**
   * Description of the collection document.
   * Provides additional context about the collection's purpose,
   * which may be more detailed than the collection's internal description.
   */
  @Field("description")
  @JsonProperty("description")
  private String description;
  
  /**
   * Name of the original file from which the collection was imported.
   * Useful for traceability and understanding the collection's origin.
   * Can be a filename, URL, or any identifier that helps track the source.
   */
  @Field("originalFileName")
  @JsonProperty("originalFileName")
  private String originalFileName;
  
  /**
   * The actual Postman Collection object.
   * Contains the complete collection structure including requests, folders,
   * variables, authentication, and all other Postman-specific configuration.
   */
  @Field("collection")
  @JsonProperty("collection")
  private Collection collection;
  
  /**
   * Tags associated with the collection for categorization and filtering.
   * Enables better organization and discovery of collections based on
   * categories, projects, teams, or any other classification system.
   */
  @Field("tags")
  @JsonProperty("tags")
  private List<String> tags;
  
  /**
   * Team or project identifier associated with this collection.
   * Helps in organizing collections by ownership or project boundaries.
   */
  @Field("team")
  @JsonProperty("team")
  private String team;
  
  /**
   * Date and time when the document was created.
   * Automatically set when creating the instance.
   */
  @Field("createdAt")
  @JsonProperty("createdAt")
  @Builder.Default
  private LocalDateTime createdAt = LocalDateTime.now();
  
  /**
   * Date and time of the last document update.
   * Should be updated whenever the collection or metadata changes.
   */
  @Field("updatedAt")
  @JsonProperty("updatedAt")
  @Builder.Default
  private LocalDateTime updatedAt = LocalDateTime.now();
  
  /**
   * Identifier of the user or system that created the document.
   * Enables authorship tracking and access control.
   */
  @Field("createdBy")
  @JsonProperty("createdBy")
  private String createdBy;
  
  /**
   * Identifier of the user or system that last modified the document.
   * Helps track who made the most recent changes.
   */
  @Field("lastModifiedBy")
  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy;
  
  /**
   * Flag indicating whether the collection is currently active/enabled.
   * Useful for temporarily disabling collections without deleting them.
   */
  @Field("active")
  @JsonProperty("active")
  @Builder.Default
  private boolean active = true;
  
}
