package es.alesqui.intelligence.dto.chat.response;

import es.alesqui.intelligence.dto.chat.reasoning.ReasoningStep;
import lombok.Data;
import org.springframework.ai.chat.model.ChatResponse;

import java.util.List;

/**
 * A data transfer object (DTO) that encapsulates the complete result
 * from the AI service after processing a user query with tools.
 * It holds the final AI response, the structured step-by-step reasoning trace,
 * and any complex objects generated by tools, such as chart data.
 */
@Data
public class ChatWithReasoningResponse {

    /**
     * The raw, final response object from the underlying Spring AI ChatClient.
     * This contains the assistant's last message, metadata, and other
     * low-level details about the generation.
     */
    private ChatResponse chatResponse;

    /**
     * A structured list of steps detailing the AI's thought process.
     * This trace includes thoughts, tool calls (with requests and responses),
     * and the final answer, allowing for interactive visualization and debugging.
     */
    private List<ReasoningStep> reasoningSteps;

    /**
     * The configuration data for a chart, captured directly from a tool call
     * like 'createChart'. This field will be populated if a chart was generated
     * during the AI's reasoning process; otherwise, it will be null.
     */
    private ChartData chart;

    /**
     * Constructs a new ChatWithReasoningResponse.
     *
     * @param chatResponse   The final ChatResponse from the AI model.
     * @param reasoningSteps The structured list of reasoning steps.
     * @param chart          Any chart data generated, or null if none.
     */
    public ChatWithReasoningResponse(ChatResponse chatResponse, List<ReasoningStep> reasoningSteps, ChartData chart) {
        this.chatResponse = chatResponse;
        this.reasoningSteps = reasoningSteps;
        this.chart = chart;
    }
}