package es.alesqui.intelligence.dto.chat.response;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * A data transfer object (DTO) that encapsulates the complete result 
 * from the AI service after processing a user query with tools.
 * It holds the final AI response, the step-by-step reasoning, and any
 * complex objects generated by tools, such as chart data.
 */
@Data
@AllArgsConstructor
public class ChatWithReasoningResponse {

    /**
     * The raw, final response object from the underlying Spring AI ChatClient.
     * This contains the assistant's last message, metadata, and other
     * low-level details about the generation.
     */
    private org.springframework.ai.chat.model.ChatResponse chatResponse;

    /**
     * A narrative string detailing the AI's thought process, including
     * which tools were called and what their results were. This is intended
     * for debugging or displaying to the user if requested.
     */
    private String formattedReasoning;

    /**
     * The configuration data for a chart, captured directly from a tool call
     * like 'createChart'. This field will be populated if a chart was generated
     * during the AI's reasoning process; otherwise, it will be null.
     */
    private ChartData chart;
}