package es.alesqui.intelligence.model.api_spec.swagger;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.models.OpenAPI;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Entity representing a Swagger/OpenAPI document stored in MongoDB.
 * 
 * This class encapsulates both document metadata (name, version, dates)
 * and the complete OpenAPI specification, allowing structured storage
 * and retrieval of API documentation.
 * 
 * The class uses Lombok to automatically generate getters, setters,
 * constructors, and builder pattern, reducing boilerplate code.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "swagger_documents")
public class SwaggerDocument {
    
    /**
     * Unique identifier of the document in MongoDB.
     * Automatically generated by MongoDB when the document is persisted.
     */
    @Id
    private String id;
    
    /**
     * Name of the Swagger document.
     * Usually extracted from the 'title' field of the OpenAPI info,
     * but can be customized by the user.
     */
    @Field("name")
    @JsonProperty("name")
    @Indexed(unique = true)
    private String name;
    
    /**
     * Description of the document.
     * Automatically extracted from the 'description' field of the OpenAPI info
     * if available, or can be set manually.
     */
    @Field("description")
    @JsonProperty("description")
    private String description;
    
    /**
     * Name of the original file from which the document was imported.
     * Useful for traceability and reference to the document's origin.
     * Can be a local filename, URL, or custom identifier.
     */
    @Field("originalFileName")
    @JsonProperty("originalFileName")
    private String originalFileName;
    
    /**
     * Complete OpenAPI specification.
     * Contains the entire Swagger/OpenAPI document structure including:
     * - General information (info)
     * - Servers (servers)
     * - Paths and operations (paths)
     * - Reusable components (components)
     * - Security schemes (security)
     * - Tags and additional metadata
     */
    @Field("openApi")
    @JsonProperty("openApi")
    private OpenAPI openApi;
    
    /**
     * Tags associated with the collection for categorization and filtering.
     * Enables better organization and discovery of collections based on
     * categories, projects, teams, or any other classification system.
     */
    @Field("tags")
    @JsonProperty("tags")
    private List<String> tags;
    
    /**
     * Team or project identifier associated with this collection.
     * Helps in organizing collections by ownership or project boundaries.
     */
    @Field("team")
    @JsonProperty("team")
    private String team;
    
    /**
     * Date and time when the document was created.
     * Automatically set when creating the instance.
     */
    @Field("createdAt")
    @JsonProperty("createdAt")
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
    
    /**
     * Date and time of the last document update.
     * Should be updated whenever the collection or metadata changes.
     */
    @Field("updatedAt")
    @JsonProperty("updatedAt")
    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();
    
    /**
     * Identifier of the user or system that created the document.
     * Enables authorship tracking and access control.
     */
    @Field("createdBy")
    @JsonProperty("createdBy")
    private String createdBy;
    
    /**
     * Identifier of the user or system that last modified the document.
     * Helps track who made the most recent changes.
     */
    @Field("lastModifiedBy")
    @JsonProperty("lastModifiedBy")
    private String lastModifiedBy;
    
    /**
     * Flag indicating whether the Swagger document is currently active/enabled.
     * Useful for temporarily disabling collections without deleting them.
     */
    @Field("active")
    @JsonProperty("active")
    @Builder.Default
    private boolean active = true;

}
